@startuml
entity TR_DVA_SOLICITUDVACIO {
  *ID_SOLICITUD : integer
}
entity TR_DVA_SOLICITUDVACIODETALLE {
  *ID_DETALLE : integer
  ID_SOLICITUD : integer (FK)
}
entity TR_DVA_SOLICITUDVACIODOC {
  *ID_DOC : integer
  ID_SOLICITUD : integer (FK)
}
entity TR_DVA_SOLICITUDVACIOSERVICIOS {
  *ID_SERVICIO : integer
  ID_SOLICITUD : integer (FK)
}
entity TR_DVA_SOLICITUDVACIOPLAN {
  *ID_PLAN : integer
  ID_SOLICITUD : integer (FK)
}
TR_DVA_SOLICITUDVACIO ||--o{ TR_DVA_SOLICITUDVACIODETALLE : detalle
TR_DVA_SOLICITUDVACIO ||--o{ TR_DVA_SOLICITUDVACIODOC : documento
TR_DVA_SOLICITUDVACIO ||--o{ TR_DVA_SOLICITUDVACIOSERVICIOS : servicio
TR_DVA_SOLICITUDVACIO ||--o{ TR_DVA_SOLICITUDVACIOPLAN : plan
@enduml
